/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use std::collections::HashMap;

#[derive(Debug, Clone)]
pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub basic_auth: Option<BasicAuth>,
    pub oauth_access_token: Option<String>,
    pub bearer_access_token: Option<String>,
    pub api_keys: HashMap<String, ApiKey>,
    /// HTTP 429 (`OVERLOADED`) retry policy applied to every generated `apis::*`
    /// operation: the request is retried with `Retry-After`/backoff before the
    /// op returns. Defaults to [`RetryPolicy::default`]; set `max_retries` to 0
    /// to disable retry. The enhanced query path ([`crate::query`]) uses its own
    /// per-call [`QueryConfig::retry`](crate::query::QueryConfig::retry) instead.
    pub retry: crate::query::RetryPolicy,
}

pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "https://api.hotdata.dev".to_owned(),
            // Computed from CARGO_PKG_VERSION at compile time so the default UA
            // always matches the shipped crate version (issue #69). Deliberately
            // ignores the generator's httpUserAgent: a regen has no idea which
            // version will publish, so baking a concrete version here lags. This
            // mirrors what ClientBuilder already does for the ergonomic surface.
            user_agent: Some(concat!("hotdata-rust/", env!("CARGO_PKG_VERSION")).to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: None,
            bearer_access_token: None,
            api_keys: HashMap::new(),
            retry: crate::query::RetryPolicy::default(),
        }
    }
}
