/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiErrorDetail : Error detail within an API error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorDetail {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl ApiErrorDetail {
    /// Error detail within an API error response
    pub fn new(code: String, message: String) -> ApiErrorDetail {
        ApiErrorDetail {
            code,
            message,
        }
    }
}

