/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttachDatabaseCatalogRequest : Request body for POST /databases/{database_id}/catalogs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachDatabaseCatalogRequest {
    /// Optional alias under which this catalog is reachable inside the database. When omitted, it is reachable by the connection's name.
    #[serde(
        rename = "alias",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub alias: Option<Option<String>>,
    #[serde(rename = "connection_id")]
    pub connection_id: String,
}

impl AttachDatabaseCatalogRequest {
    /// Request body for POST /databases/{database_id}/catalogs
    pub fn new(connection_id: String) -> AttachDatabaseCatalogRequest {
        AttachDatabaseCatalogRequest {
            alias: None,
            connection_id,
        }
    }
}
