/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchCreateUploadResponse : Response body for `POST /v1/uploads/batch`: one created session per requested file, in request order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchCreateUploadResponse {
    #[serde(rename = "uploads")]
    pub uploads: Vec<models::UploadSessionResponse>,
}

impl BatchCreateUploadResponse {
    /// Response body for `POST /v1/uploads/batch`: one created session per requested file, in request order.
    pub fn new(uploads: Vec<models::UploadSessionResponse>) -> BatchCreateUploadResponse {
        BatchCreateUploadResponse { uploads }
    }
}
