/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BooleanProfileDetail : Boolean column.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BooleanProfileDetail {
    /// Number of false values
    #[serde(rename = "false_count")]
    pub false_count: i64,
    /// Number of true values
    #[serde(rename = "true_count")]
    pub true_count: i64,
}

impl BooleanProfileDetail {
    /// Boolean column.
    pub fn new(false_count: i64, true_count: i64) -> BooleanProfileDetail {
        BooleanProfileDetail {
            false_count,
            true_count,
        }
    }
}

