/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CategoryValueInfo : A distinct value with its frequency count, used in categorical profiles.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoryValueInfo {
    /// Number of occurrences
    #[serde(rename = "count")]
    pub count: i64,
    /// The distinct value (as a string, or null)
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<serde_json::Value>,
}

impl CategoryValueInfo {
    /// A distinct value with its frequency count, used in categorical profiles.
    pub fn new(count: i64, value: Option<serde_json::Value>) -> CategoryValueInfo {
        CategoryValueInfo {
            count,
            value,
        }
    }
}

