/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ColumnProfileDetailOneOf2 {
    /// Maximum value (string to preserve precision for large integers and decimals)
    #[serde(rename = "max")]
    pub max: String,
    /// Arithmetic mean
    #[serde(rename = "mean")]
    pub mean: f64,
    /// Minimum value (string to preserve precision for large integers and decimals)
    #[serde(rename = "min")]
    pub min: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ColumnProfileDetailOneOf2 {
    pub fn new(max: String, mean: f64, min: String, r#type: Type) -> ColumnProfileDetailOneOf2 {
        ColumnProfileDetailOneOf2 {
            max,
            mean,
            min,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "numeric")]
    Numeric,
}

impl Default for Type {
    fn default() -> Type {
        Self::Numeric
    }
}

