/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ColumnInfo : Column metadata for API responses
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ColumnInfo {
    #[serde(rename = "data_type")]
    pub data_type: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nullable")]
    pub nullable: bool,
}

impl ColumnInfo {
    /// Column metadata for API responses
    pub fn new(data_type: String, name: String, nullable: bool) -> ColumnInfo {
        ColumnInfo {
            data_type,
            name,
            nullable,
        }
    }
}

