/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ColumnProfileDetail : Type-specific column profile detail. The `type` discriminator field determines which variant is present. Profile type is chosen based on the column's Arrow data type and cardinality:  - **categorical**: Text or numeric columns with ≤200 distinct values. Lists each value with its frequency. - **text**: Text columns with >200 distinct values. Reports string length statistics. - **numeric**: Numeric columns with >200 distinct values. Reports min, max, and mean. - **temporal**: Date and timestamp columns. Reports min and max as ISO-8601 strings. - **boolean**: Boolean columns. Reports true and false counts.
/// Type-specific column profile detail. The `type` discriminator field determines which variant is present. Profile type is chosen based on the column's Arrow data type and cardinality:  - **categorical**: Text or numeric columns with ≤200 distinct values. Lists each value with its frequency. - **text**: Text columns with >200 distinct values. Reports string length statistics. - **numeric**: Numeric columns with >200 distinct values. Reports min, max, and mean. - **temporal**: Date and timestamp columns. Reports min and max as ISO-8601 strings. - **boolean**: Boolean columns. Reports true and false counts.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ColumnProfileDetail {
    ColumnProfileDetailOneOf(Box<models::ColumnProfileDetailOneOf>),
    ColumnProfileDetailOneOf1(Box<models::ColumnProfileDetailOneOf1>),
    ColumnProfileDetailOneOf2(Box<models::ColumnProfileDetailOneOf2>),
    ColumnProfileDetailOneOf3(Box<models::ColumnProfileDetailOneOf3>),
    ColumnProfileDetailOneOf4(Box<models::ColumnProfileDetailOneOf4>),
}

impl Default for ColumnProfileDetail {
    fn default() -> Self {
        Self::ColumnProfileDetailOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "categorical")]
    Categorical,
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "numeric")]
    Numeric,
    #[serde(rename = "temporal")]
    Temporal,
    #[serde(rename = "boolean")]
    Boolean,
}

impl Default for Type {
    fn default() -> Type {
        Self::Categorical
    }
}

