/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ColumnTypeSpec : A column type plus the parameters that cannot be expressed by a bare name.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ColumnTypeSpec {
    /// Total number of digits for `DECIMAL` / `NUMERIC` (1–38).
    #[serde(
        rename = "precision",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub precision: Option<Option<i32>>,
    /// Number of digits after the decimal point for `DECIMAL` / `NUMERIC`. Requires `precision`, and cannot exceed it.
    #[serde(
        rename = "scale",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scale: Option<Option<i32>>,
    /// The type name, e.g. `\"DECIMAL\"`, `\"TIMESTAMP\"`, `\"VARCHAR\"`.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ColumnTypeSpec {
    /// A column type plus the parameters that cannot be expressed by a bare name.
    pub fn new(r#type: String) -> ColumnTypeSpec {
        ColumnTypeSpec {
            precision: None,
            scale: None,
            r#type,
        }
    }
}
