/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ColumnProfileDetailOneOf4 : Boolean column.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ColumnProfileDetailOneOf4 {
    /// Number of false values
    #[serde(rename = "false_count")]
    pub false_count: i64,
    /// Number of true values
    #[serde(rename = "true_count")]
    pub true_count: i64,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ColumnProfileDetailOneOf4 {
    /// Boolean column.
    pub fn new(false_count: i64, true_count: i64, r#type: Type) -> ColumnProfileDetailOneOf4 {
        ColumnProfileDetailOneOf4 {
            false_count,
            true_count,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "boolean")]
    Boolean,
}

impl Default for Type {
    fn default() -> Type {
        Self::Boolean
    }
}

