/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ColumnDefinition : Column type specification - either a simple type string or detailed spec with properties.  Simple form: `\"VARCHAR\"`, `\"INT\"`, `\"DATE\"` Detailed form: `{ \"type\": \"DECIMAL\", \"precision\": 10, \"scale\": 2 }`
/// Column type specification - either a simple type string or detailed spec with properties.  Simple form: `\"VARCHAR\"`, `\"INT\"`, `\"DATE\"` Detailed form: `{ \"type\": \"DECIMAL\", \"precision\": 10, \"scale\": 2 }`
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ColumnDefinition {
    /// Simple type name (e.g., \"VARCHAR\", \"INT\", \"DATE\")
    String(String),
    ColumnTypeSpec(Box<models::ColumnTypeSpec>),
}

impl Default for ColumnDefinition {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

