/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ColumnProfileDetailOneOf3 : Date or timestamp column.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ColumnProfileDetailOneOf3 {
    /// Latest value as ISO-8601 string
    #[serde(rename = "max")]
    pub max: String,
    /// Earliest value as ISO-8601 string
    #[serde(rename = "min")]
    pub min: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ColumnProfileDetailOneOf3 {
    /// Date or timestamp column.
    pub fn new(max: String, min: String, r#type: Type) -> ColumnProfileDetailOneOf3 {
        ColumnProfileDetailOneOf3 {
            max,
            min,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "temporal")]
    Temporal,
}

impl Default for Type {
    fn default() -> Type {
        Self::Temporal
    }
}

