/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ColumnProfileDetailOneOf : Low-cardinality column (≤200 distinct values). Applies to text and numeric columns. Values are sorted by frequency descending.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ColumnProfileDetailOneOf {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Distinct values with their counts, ordered by count descending
    #[serde(rename = "values")]
    pub values: Vec<models::CategoryValueInfo>,
}

impl ColumnProfileDetailOneOf {
    /// Low-cardinality column (≤200 distinct values). Applies to text and numeric columns. Values are sorted by frequency descending.
    pub fn new(r#type: Type, values: Vec<models::CategoryValueInfo>) -> ColumnProfileDetailOneOf {
        ColumnProfileDetailOneOf {
            r#type,
            values,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "categorical")]
    Categorical,
}

impl Default for Type {
    fn default() -> Type {
        Self::Categorical
    }
}

