/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectionSchemaError : Error details for a failed connection schema refresh
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionSchemaError {
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "error")]
    pub error: String,
}

impl ConnectionSchemaError {
    /// Error details for a failed connection schema refresh
    pub fn new(connection_id: String, error: String) -> ConnectionSchemaError {
        ConnectionSchemaError {
            connection_id,
            error,
        }
    }
}

