/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateIndexRequest : Request body for POST .../indexes
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIndexRequest {
    #[serde(rename = "index_name")]
    pub index_name: String,
    /// Index type: \"sorted\" (default), \"bm25\", or \"vector\"
    #[serde(rename = "index_type", skip_serializing_if = "Option::is_none")]
    pub index_type: Option<String>,
    /// Distance metric for vector indexes: \"l2\" (default), \"cosine\", or \"dot\". Only relevant when index_type = \"vector\".
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<String>,
    #[serde(rename = "sort_columns", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sort_columns: Option<Option<Vec<String>>>,
    /// Text columns for BM25 indexes
    #[serde(rename = "text_columns", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub text_columns: Option<Option<Vec<String>>>,
    /// Vector column for vector indexes (exactly one entry required)
    #[serde(rename = "vector_columns", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vector_columns: Option<Option<Vec<String>>>,
}

impl CreateIndexRequest {
    /// Request body for POST .../indexes
    pub fn new(index_name: String) -> CreateIndexRequest {
        CreateIndexRequest {
            index_name,
            index_type: None,
            metric: None,
            sort_columns: None,
            text_columns: None,
            vector_columns: None,
        }
    }
}

