/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkspaceRequest {
    /// Name for the new workspace.
    #[serde(rename = "name")]
    pub name: String,
    /// Target organization. Defaults to the user's current organization.
    #[serde(rename = "organization_public_id", skip_serializing_if = "Option::is_none")]
    pub organization_public_id: Option<String>,
}

impl CreateWorkspaceRequest {
    pub fn new(name: String) -> CreateWorkspaceRequest {
        CreateWorkspaceRequest {
            name,
            organization_public_id: None,
        }
    }
}

