/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkspaceResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "workspace")]
    pub workspace: Box<models::WorkspaceDetail>,
}

impl CreateWorkspaceResponse {
    pub fn new(ok: bool, workspace: models::WorkspaceDetail) -> CreateWorkspaceResponse {
        CreateWorkspaceResponse {
            ok,
            workspace: Box::new(workspace),
        }
    }
}

