/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSecretRequest : Request body for POST /secrets
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSecretRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl CreateSecretRequest {
    /// Request body for POST /secrets
    pub fn new(name: String, value: String) -> CreateSecretRequest {
        CreateSecretRequest {
            name,
            value,
        }
    }
}

