/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSecretResponse : Response body for POST /secrets
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSecretResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateSecretResponse {
    /// Response body for POST /secrets
    pub fn new(created_at: String, id: String, name: String) -> CreateSecretResponse {
        CreateSecretResponse {
            created_at,
            id,
            name,
        }
    }
}

