/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateEmbeddingProviderResponse : Response body for POST /embedding-providers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEmbeddingProviderResponse {
    #[serde(rename = "config", deserialize_with = "Option::deserialize")]
    pub config: Option<serde_json::Value>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "provider_type")]
    pub provider_type: String,
}

impl CreateEmbeddingProviderResponse {
    /// Response body for POST /embedding-providers
    pub fn new(
        config: Option<serde_json::Value>,
        created_at: String,
        id: String,
        name: String,
        provider_type: String,
    ) -> CreateEmbeddingProviderResponse {
        CreateEmbeddingProviderResponse {
            config,
            created_at,
            id,
            name,
            provider_type,
        }
    }
}
