/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DatabaseCountResponse : Response body for GET /databases/count.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseCountResponse {
    /// Total databases matching the filters, across all pages.
    #[serde(rename = "total")]
    pub total: i64,
}

impl DatabaseCountResponse {
    /// Response body for GET /databases/count.
    pub fn new(total: i64) -> DatabaseCountResponse {
        DatabaseCountResponse { total }
    }
}
