/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DatabaseContextEntry : One context entry returned by the API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseContextEntry {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl DatabaseContextEntry {
    /// One context entry returned by the API.
    pub fn new(content: String, name: String, updated_at: String) -> DatabaseContextEntry {
        DatabaseContextEntry {
            content,
            name,
            updated_at,
        }
    }
}
