/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DatabaseDefaultSchemaDecl : One schema declaration inside the database's default catalog, supplied at create time. `tables` defaults to empty, so you can declare just a schema name and add tables later.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseDefaultSchemaDecl {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tables", skip_serializing_if = "Option::is_none")]
    pub tables: Option<Vec<models::DatabaseDefaultTableDecl>>,
}

impl DatabaseDefaultSchemaDecl {
    /// One schema declaration inside the database's default catalog, supplied at create time. `tables` defaults to empty, so you can declare just a schema name and add tables later.
    pub fn new(name: String) -> DatabaseDefaultSchemaDecl {
        DatabaseDefaultSchemaDecl { name, tables: None }
    }
}
