/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DatabaseSummary : Summary item in GET /databases
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseSummary {
    /// Name the database's default catalog answers to inside its query scope.
    #[serde(rename = "default_catalog")]
    pub default_catalog: String,
    #[serde(rename = "expires_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl DatabaseSummary {
    /// Summary item in GET /databases
    pub fn new(default_catalog: String, id: String) -> DatabaseSummary {
        DatabaseSummary {
            default_catalog,
            expires_at: None,
            id,
            name: None,
        }
    }
}

