/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteDatabaseBatchResponse : Response body for DELETE /databases/bulk/{batch_id}.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteDatabaseBatchResponse {
    #[serde(rename = "batch_id")]
    pub batch_id: String,
    /// How many databases were removed.
    #[serde(rename = "deleted_count")]
    pub deleted_count: i64,
}

impl DeleteDatabaseBatchResponse {
    /// Response body for DELETE /databases/bulk/{batch_id}.
    pub fn new(batch_id: String, deleted_count: i64) -> DeleteDatabaseBatchResponse {
        DeleteDatabaseBatchResponse {
            batch_id,
            deleted_count,
        }
    }
}
