/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteSandboxResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl DeleteSandboxResponse {
    pub fn new(ok: bool, deleted: bool) -> DeleteSandboxResponse {
        DeleteSandboxResponse {
            ok,
            deleted,
        }
    }
}

