/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// Machine-readable error code.
    #[serde(rename = "error")]
    pub error: String,
}

impl Error {
    pub fn new(error: String) -> Error {
        Error {
            error,
        }
    }
}

