/*
 * Hotdata API
 *
 * Powerful data platform API for instant databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FinalizeUploadPart : One part of a multi-part upload, supplied at finalize. Single-`PUT` uploads have no parts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinalizeUploadPart {
    /// The `ETag` response header returned by that part's `PUT`.
    #[serde(rename = "e_tag")]
    pub e_tag: String,
    /// The 1-based part number you uploaded this part as.
    #[serde(rename = "part_number")]
    pub part_number: i32,
}

impl FinalizeUploadPart {
    /// One part of a multi-part upload, supplied at finalize. Single-`PUT` uploads have no parts.
    pub fn new(e_tag: String, part_number: i32) -> FinalizeUploadPart {
        FinalizeUploadPart { e_tag, part_number }
    }
}
