/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FinalizeUploadPart : One part of a multi-part upload, supplied at finalize. Reserved for a future multi-part mode; single-`PUT` uploads have no parts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinalizeUploadPart {
    /// The entity tag (ETag) storage returned for the uploaded part.
    #[serde(rename = "e_tag")]
    pub e_tag: String,
    /// 1-based part number, as reported by storage for the part.
    #[serde(rename = "part_number")]
    pub part_number: i32,
}

impl FinalizeUploadPart {
    /// One part of a multi-part upload, supplied at finalize. Reserved for a future multi-part mode; single-`PUT` uploads have no parts.
    pub fn new(e_tag: String, part_number: i32) -> FinalizeUploadPart {
        FinalizeUploadPart { e_tag, part_number }
    }
}
