/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FinalizeUploadRequest : Request body for `POST /v1/uploads/{upload_id}/finalize`.  Finalizing confirms the bytes were uploaded and makes the upload usable as managed-table contents. The request body is optional for single-`PUT` uploads; send `parts` only for a future multi-part upload.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinalizeUploadRequest {
    /// Parts to assemble, for a multi-part upload. Omit for single-`PUT` uploads (the common case).
    #[serde(
        rename = "parts",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parts: Option<Option<Vec<models::FinalizeUploadPart>>>,
}

impl FinalizeUploadRequest {
    /// Request body for `POST /v1/uploads/{upload_id}/finalize`.  Finalizing confirms the bytes were uploaded and makes the upload usable as managed-table contents. The request body is optional for single-`PUT` uploads; send `parts` only for a future multi-part upload.
    pub fn new() -> FinalizeUploadRequest {
        FinalizeUploadRequest { parts: None }
    }
}
