/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSecretResponse : Response body for GET /secrets/{name}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSecretResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl GetSecretResponse {
    /// Response body for GET /secrets/{name}
    pub fn new(created_at: String, name: String, updated_at: String) -> GetSecretResponse {
        GetSecretResponse {
            created_at,
            name,
            updated_at,
        }
    }
}

