/*
 * Hotdata API
 *
 * Powerful data platform API for instant databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndexInfoResponse : Result payload for a `create_index` job, and response for index endpoints.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexInfoResponse {
    /// How this vector index organises the vectors it searches: `hnsw` or `ivf`. Absent for BM25 and sorted indexes.
    #[serde(
        rename = "algorithm",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub algorithm: Option<Option<String>>,
    #[serde(rename = "columns")]
    pub columns: Vec<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "index_name")]
    pub index_name: String,
    #[serde(rename = "index_type")]
    pub index_type: String,
    /// Distance metric this index was built with. Only present for vector indexes.
    #[serde(
        rename = "metric",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metric: Option<Option<String>>,
    /// Number of clusters an `ivf` index was built with. This can be smaller than the `nlist` requested when the index was created, because the number is capped by how many vectors the clusters were fitted to. Absent for every other kind of index.
    #[serde(
        rename = "nlist",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nlist: Option<Option<i64>>,
    /// How much of an `ivf` index a search reads, as a fraction greater than 0 and at most 1, when the index was created with one. When absent, the server chooses how much each search reads: a width measured on this index's own data when it was built, scaled to the number of results a search asks for, or a server default when no measurement could be made. Absent for every other kind of index.
    #[serde(
        rename = "probe_fraction",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub probe_fraction: Option<Option<f64>>,
    /// Source text column for an embedding-backed vector index. A query searches it via `vector_distance(<source_column>, …)`; the indexed `columns` hold the generated embedding column instead. Absent for BM25, sorted, and direct (existing-column) vector indexes.
    #[serde(
        rename = "source_column",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_column: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: models::IndexStatus,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// How precisely this vector index stores each number of a vector. Always present for an `ivf` index, which stores `int8` unless it was created with another precision. For an `hnsw` index it is present only when the index was created with an explicit precision; absent means it stores at the same precision as the column. Absent for BM25 and sorted indexes.
    #[serde(
        rename = "vector_precision",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vector_precision: Option<Option<String>>,
}

impl IndexInfoResponse {
    /// Result payload for a `create_index` job, and response for index endpoints.
    pub fn new(
        columns: Vec<String>,
        created_at: String,
        index_name: String,
        index_type: String,
        status: models::IndexStatus,
        updated_at: String,
    ) -> IndexInfoResponse {
        IndexInfoResponse {
            algorithm: None,
            columns,
            created_at,
            index_name,
            index_type,
            metric: None,
            nlist: None,
            probe_fraction: None,
            source_column: None,
            status,
            updated_at,
            vector_precision: None,
        }
    }
}
