/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndexInfoResponse : Response for index endpoints.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexInfoResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "index_name")]
    pub index_name: String,
    #[serde(rename = "index_type")]
    pub index_type: String,
    /// Distance metric this index was built with. Only present for vector indexes.
    #[serde(rename = "metric", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metric: Option<Option<String>>,
    #[serde(rename = "sort_columns")]
    pub sort_columns: Vec<String>,
    #[serde(rename = "status")]
    pub status: models::IndexStatus,
    #[serde(rename = "text_columns")]
    pub text_columns: Vec<String>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "vector_columns")]
    pub vector_columns: Vec<String>,
}

impl IndexInfoResponse {
    /// Response for index endpoints.
    pub fn new(created_at: String, index_name: String, index_type: String, sort_columns: Vec<String>, status: models::IndexStatus, text_columns: Vec<String>, updated_at: String, vector_columns: Vec<String>) -> IndexInfoResponse {
        IndexInfoResponse {
            created_at,
            index_name,
            index_type,
            metric: None,
            sort_columns,
            status,
            text_columns,
            updated_at,
            vector_columns,
        }
    }
}

