/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListUploadsResponse : Response body for GET /v1/files
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListUploadsResponse {
    #[serde(rename = "uploads")]
    pub uploads: Vec<models::UploadInfo>,
}

impl ListUploadsResponse {
    /// Response body for GET /v1/files
    pub fn new(uploads: Vec<models::UploadInfo>) -> ListUploadsResponse {
        ListUploadsResponse {
            uploads,
        }
    }
}

