/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListConnectionsResponse : Response body for GET /connections
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListConnectionsResponse {
    #[serde(rename = "connections")]
    pub connections: Vec<models::ConnectionInfo>,
}

impl ListConnectionsResponse {
    /// Response body for GET /connections
    pub fn new(connections: Vec<models::ConnectionInfo>) -> ListConnectionsResponse {
        ListConnectionsResponse {
            connections,
        }
    }
}

