/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListEmbeddingProvidersResponse : Response body for GET /embedding-providers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEmbeddingProvidersResponse {
    #[serde(rename = "embedding_providers")]
    pub embedding_providers: Vec<models::EmbeddingProviderResponse>,
}

impl ListEmbeddingProvidersResponse {
    /// Response body for GET /embedding-providers
    pub fn new(
        embedding_providers: Vec<models::EmbeddingProviderResponse>,
    ) -> ListEmbeddingProvidersResponse {
        ListEmbeddingProvidersResponse {
            embedding_providers,
        }
    }
}
