/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListJobsResponse : Response body for GET /v1/jobs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListJobsResponse {
    #[serde(rename = "jobs")]
    pub jobs: Vec<models::JobStatusResponse>,
}

impl ListJobsResponse {
    /// Response body for GET /v1/jobs
    pub fn new(jobs: Vec<models::JobStatusResponse>) -> ListJobsResponse {
        ListJobsResponse {
            jobs,
        }
    }
}

