/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListIndexesPageResponse : Response body for `GET /v1/indexes` (paginated, cross-table).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListIndexesPageResponse {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "indexes")]
    pub indexes: Vec<models::IndexEntryResponse>,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(
        rename = "next_cursor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_cursor: Option<Option<String>>,
}

impl ListIndexesPageResponse {
    /// Response body for `GET /v1/indexes` (paginated, cross-table).
    pub fn new(
        count: i32,
        has_more: bool,
        indexes: Vec<models::IndexEntryResponse>,
        limit: i32,
    ) -> ListIndexesPageResponse {
        ListIndexesPageResponse {
            count,
            has_more,
            indexes,
            limit,
            next_cursor: None,
        }
    }
}
