/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSandboxesResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "sandboxes")]
    pub sandboxes: Vec<models::Sandbox>,
}

impl ListSandboxesResponse {
    pub fn new(ok: bool, sandboxes: Vec<models::Sandbox>) -> ListSandboxesResponse {
        ListSandboxesResponse { ok, sandboxes }
    }
}
