/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListDatabasesResponse : Response body for GET /databases
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDatabasesResponse {
    #[serde(rename = "databases")]
    pub databases: Vec<models::DatabaseSummary>,
}

impl ListDatabasesResponse {
    /// Response body for GET /databases
    pub fn new(databases: Vec<models::DatabaseSummary>) -> ListDatabasesResponse {
        ListDatabasesResponse { databases }
    }
}
