/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListDatabaseContextsResponse : Response body for GET `/v1/databases/{database_id}/context`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDatabaseContextsResponse {
    #[serde(rename = "contexts")]
    pub contexts: Vec<models::DatabaseContextEntry>,
}

impl ListDatabaseContextsResponse {
    /// Response body for GET `/v1/databases/{database_id}/context`.
    pub fn new(contexts: Vec<models::DatabaseContextEntry>) -> ListDatabaseContextsResponse {
        ListDatabaseContextsResponse { contexts }
    }
}
