/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListDatabasesResponse : Response body for GET /databases. Results are returned one page at a time, newest first. When `has_more` is true, pass `next_cursor` back as the `cursor` query parameter to fetch the following page.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDatabasesResponse {
    /// Number of databases returned in this page.
    #[serde(
        rename = "count",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub count: Option<Option<i32>>,
    #[serde(rename = "databases")]
    pub databases: Vec<models::DatabaseSummary>,
    /// Whether more databases exist beyond this page.
    #[serde(
        rename = "has_more",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_more: Option<Option<bool>>,
    /// Page size applied to this response (after clamping to the maximum).
    #[serde(
        rename = "limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit: Option<Option<i32>>,
    /// Opaque cursor for the next page; present only when `has_more` is true.
    #[serde(
        rename = "next_cursor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_cursor: Option<Option<String>>,
}

impl ListDatabasesResponse {
    /// Response body for GET /databases. Results are returned one page at a time, newest first. When `has_more` is true, pass `next_cursor` back as the `cursor` query parameter to fetch the following page.
    pub fn new(databases: Vec<models::DatabaseSummary>) -> ListDatabasesResponse {
        ListDatabasesResponse {
            count: None,
            databases,
            has_more: None,
            limit: None,
            next_cursor: None,
        }
    }
}
