/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListIndexesResponse : Response body for GET .../indexes
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListIndexesResponse {
    #[serde(rename = "indexes")]
    pub indexes: Vec<models::IndexInfoResponse>,
}

impl ListIndexesResponse {
    /// Response body for GET .../indexes
    pub fn new(indexes: Vec<models::IndexInfoResponse>) -> ListIndexesResponse {
        ListIndexesResponse {
            indexes,
        }
    }
}

