/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWorkspaces200Response {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "workspaces")]
    pub workspaces: Vec<models::WorkspaceListItem>,
}

impl ListWorkspaces200Response {
    pub fn new(ok: bool, workspaces: Vec<models::WorkspaceListItem>) -> ListWorkspaces200Response {
        ListWorkspaces200Response {
            ok,
            workspaces,
        }
    }
}

