/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListSecretsResponse : Response body for GET /secrets
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSecretsResponse {
    #[serde(rename = "secrets")]
    pub secrets: Vec<models::SecretMetadataResponse>,
}

impl ListSecretsResponse {
    /// Response body for GET /secrets
    pub fn new(secrets: Vec<models::SecretMetadataResponse>) -> ListSecretsResponse {
        ListSecretsResponse {
            secrets,
        }
    }
}

