/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListConnectionTypesResponse {
    #[serde(rename = "connection_types")]
    pub connection_types: Vec<models::ConnectionTypeSummary>,
}

impl ListConnectionTypesResponse {
    pub fn new(connection_types: Vec<models::ConnectionTypeSummary>) -> ListConnectionTypesResponse {
        ListConnectionTypesResponse {
            connection_types,
        }
    }
}

