/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoadManagedTableResponse : Response body for `POST /v1/connections/{connection_id}/schemas/{schema}/tables/{table}/loads`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoadManagedTableResponse {
    /// Schema of the loaded table, as JSON.
    #[serde(rename = "arrow_schema_json")]
    pub arrow_schema_json: String,
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    /// Total rows in the published parquet file.
    #[serde(rename = "row_count")]
    pub row_count: i64,
    #[serde(rename = "schema_name")]
    pub schema_name: String,
    #[serde(rename = "table_name")]
    pub table_name: String,
}

impl LoadManagedTableResponse {
    /// Response body for `POST /v1/connections/{connection_id}/schemas/{schema}/tables/{table}/loads`.
    pub fn new(
        arrow_schema_json: String,
        connection_id: String,
        row_count: i64,
        schema_name: String,
        table_name: String,
    ) -> LoadManagedTableResponse {
        LoadManagedTableResponse {
            arrow_schema_json,
            connection_id,
            row_count,
            schema_name,
            table_name,
        }
    }
}
