/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ManagedTableResponse : Response body for a successful add-table request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManagedTableResponse {
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "schema")]
    pub schema: String,
    #[serde(rename = "table")]
    pub table: String,
}

impl ManagedTableResponse {
    /// Response body for a successful add-table request.
    pub fn new(connection_id: String, schema: String, table: String) -> ManagedTableResponse {
        ManagedTableResponse {
            connection_id,
            schema,
            table,
        }
    }
}

