/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MintedUploadPartResponse : One minted part URL.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MintedUploadPartResponse {
    /// The 1-based part number this URL is for.
    #[serde(rename = "part_number")]
    pub part_number: i32,
    /// Short-lived URL to `PUT` this part's bytes to. Keep the response's `ETag` and pass the `{part_number, e_tag}` pair to finalize.
    #[serde(rename = "url")]
    pub url: String,
}

impl MintedUploadPartResponse {
    /// One minted part URL.
    pub fn new(part_number: i32, url: String) -> MintedUploadPartResponse {
        MintedUploadPartResponse { part_number, url }
    }
}
