/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NumericProfileDetail : High-cardinality numeric column (>200 distinct values).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NumericProfileDetail {
    /// Maximum value (string to preserve precision for large integers and decimals)
    #[serde(rename = "max")]
    pub max: String,
    /// Arithmetic mean
    #[serde(rename = "mean")]
    pub mean: f64,
    /// Minimum value (string to preserve precision for large integers and decimals)
    #[serde(rename = "min")]
    pub min: String,
}

impl NumericProfileDetail {
    /// High-cardinality numeric column (>200 distinct values).
    pub fn new(max: String, mean: f64, min: String) -> NumericProfileDetail {
        NumericProfileDetail {
            max,
            mean,
            min,
        }
    }
}

