/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryRequest : Request body for POST /query
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryRequest {
    #[serde(rename = "sql")]
    pub sql: String,
}

impl QueryRequest {
    /// Request body for POST /query
    pub fn new(sql: String) -> QueryRequest {
        QueryRequest {
            sql,
        }
    }
}

