/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Sandbox {
    #[serde(rename = "public_id")]
    pub public_id: String,
    #[serde(rename = "name")]
    pub name: String,
    /// Freeform markdown notes attached to the sandbox.
    #[serde(rename = "markdown")]
    pub markdown: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Sandbox {
    pub fn new(public_id: String, name: String, markdown: String, created_at: String, updated_at: String) -> Sandbox {
        Sandbox {
            public_id,
            name,
            markdown,
            created_at,
            updated_at,
        }
    }
}

