/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "sandbox")]
    pub sandbox: Box<models::Sandbox>,
}

impl SandboxResponse {
    pub fn new(ok: bool, sandbox: models::Sandbox) -> SandboxResponse {
        SandboxResponse {
            ok,
            sandbox: Box::new(sandbox),
        }
    }
}
