/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SavedQueryVersionInfo : Single saved query version
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SavedQueryVersionInfo {
    #[serde(rename = "category", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category: Option<Option<serde_json::Value>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "has_aggregation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_aggregation: Option<Option<serde_json::Value>>,
    #[serde(rename = "has_group_by", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_group_by: Option<Option<serde_json::Value>>,
    #[serde(rename = "has_join", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_join: Option<Option<serde_json::Value>>,
    #[serde(rename = "has_limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_limit: Option<Option<serde_json::Value>>,
    #[serde(rename = "has_order_by", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_order_by: Option<Option<serde_json::Value>>,
    #[serde(rename = "has_predicate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_predicate: Option<Option<serde_json::Value>>,
    #[serde(rename = "num_tables", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub num_tables: Option<Option<serde_json::Value>>,
    #[serde(rename = "sql")]
    pub sql: String,
    #[serde(rename = "sql_hash")]
    pub sql_hash: String,
    #[serde(rename = "table_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub table_size: Option<Option<serde_json::Value>>,
    #[serde(rename = "version")]
    pub version: i32,
}

impl SavedQueryVersionInfo {
    /// Single saved query version
    pub fn new(created_at: String, sql: String, sql_hash: String, version: i32) -> SavedQueryVersionInfo {
        SavedQueryVersionInfo {
            category: None,
            created_at,
            has_aggregation: None,
            has_group_by: None,
            has_join: None,
            has_limit: None,
            has_order_by: None,
            has_predicate: None,
            num_tables: None,
            sql,
            sql_hash,
            table_size: None,
            version,
        }
    }
}

