/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretMetadataResponse : Single secret metadata for API responses
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretMetadataResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl SecretMetadataResponse {
    /// Single secret metadata for API responses
    pub fn new(created_at: String, name: String, updated_at: String) -> SecretMetadataResponse {
        SecretMetadataResponse {
            created_at,
            name,
            updated_at,
        }
    }
}

