/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TableRefreshError : Error details for a failed table refresh
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableRefreshError {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "schema_name")]
    pub schema_name: String,
    #[serde(rename = "table_name")]
    pub table_name: String,
}

impl TableRefreshError {
    /// Error details for a failed table refresh
    pub fn new(error: String, schema_name: String, table_name: String) -> TableRefreshError {
        TableRefreshError {
            error,
            schema_name,
            table_name,
        }
    }
}

