/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TemporalProfileDetail : Date or timestamp column.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemporalProfileDetail {
    /// Latest value as ISO-8601 string
    #[serde(rename = "max")]
    pub max: String,
    /// Earliest value as ISO-8601 string
    #[serde(rename = "min")]
    pub min: String,
}

impl TemporalProfileDetail {
    /// Date or timestamp column.
    pub fn new(max: String, min: String) -> TemporalProfileDetail {
        TemporalProfileDetail {
            max,
            min,
        }
    }
}

