/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateSecretRequest : Request body for PUT /secrets/{name}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSecretRequest {
    #[serde(rename = "value")]
    pub value: String,
}

impl UpdateSecretRequest {
    /// Request body for PUT /secrets/{name}
    pub fn new(value: String) -> UpdateSecretRequest {
        UpdateSecretRequest {
            value,
        }
    }
}

