/*
 * Hotdata API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateSecretResponse : Response body for PUT /secrets/{name}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSecretResponse {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl UpdateSecretResponse {
    /// Response body for PUT /secrets/{name}
    pub fn new(name: String, updated_at: String) -> UpdateSecretResponse {
        UpdateSecretResponse {
            name,
            updated_at,
        }
    }
}

