/*
 * Hotdata API
 *
 * Powerful data platform API for managed databases, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpsertDatabaseContextResponse : Response body for POST `/v1/databases/{database_id}/context`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertDatabaseContextResponse {
    #[serde(rename = "context")]
    pub context: Box<models::DatabaseContextEntry>,
}

impl UpsertDatabaseContextResponse {
    /// Response body for POST `/v1/databases/{database_id}/context`.
    pub fn new(context: models::DatabaseContextEntry) -> UpsertDatabaseContextResponse {
        UpsertDatabaseContextResponse {
            context: Box::new(context),
        }
    }
}
