/*
 * HotData API
 *
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceListItem {
    #[serde(rename = "public_id")]
    pub public_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "favorite")]
    pub favorite: bool,
    #[serde(rename = "provision_status")]
    pub provision_status: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
}

impl WorkspaceListItem {
    pub fn new(public_id: String, name: String, active: bool, favorite: bool, provision_status: String, namespace: String) -> WorkspaceListItem {
        WorkspaceListItem {
            public_id,
            name,
            active,
            favorite,
            provision_status,
            namespace,
        }
    }
}

